### ISSUE TITLE
Rspec-core requirement

### ISSUE THREAD

**Issue by adeleglise** [mipmip/rspec_testlink_formatters#1]
Hi,

I know that it's been a long time since you make this code, but can you tell me how I can use it with a recent version of rspec-core ?

`Gem::ConflictError: Unable to activate rspec_testlink_formatters-0.0.3, because rspec-core-3.5.4 conflicts with rspec-core (~> 3.1.0)`

Thanks

**Comment by mipmip** [comment]
It's not maintained anymore, but you could fork this repo and change the runtime versions in rspec_testlink_formatters.gemspec

**Comment by adeleglise** [comment]
Ok thanks, I've tried changing the requirements manually in this file, but it's still complaining.

I've changed it on my local file, after running "gem install rspec_testlink_formatters", maybe it's the problem.

Anyway, thanks a lot for your work and your answer :)
